# Generated by Django 5.0.7 on 2024-09-02 13:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrapper', '0010_scrapeddata_amazon_shipping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('pds', models.FloatField(default=0)),
                ('pcs', models.FloatField(default=0)),
                ('opps', models.FloatField(default=0)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amazon_sold_by', models.CharField(blank=True, max_length=20, null=True)),
                ('compliance_flags', models.JSONField(default=dict)),
                ('user_accounts', models.JSONField(default=list)),
                ('on_promo', models.BooleanField(default=False)),
                ('my_price', models.FloatField(default=0)),
                ('scraped_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_data', to='scrapper.scrapeddata')),
            ],
        ),
    ]
