# Generated by Django 5.0.7 on 2024-10-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceData',
        ),
    ]
