"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
from urllib.parse import quote
from datetime import timedelta
from environ import Env
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = Env(
    DEBUG=(bool, False),
)
ENV_FILE = BASE_DIR / "project" / ".env"
if ENV_FILE.exists():
    Env.read_env(ENV_FILE)

ENVIRONMENT = env('ENVIRONMENT', default='development')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=ENVIRONMENT == 'development')


ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=['localhost', '127.0.0.1'],
)
ADMIN_URL = env("ADMIN_URL", default="admin/")

CSRF_TRUSTED_ORIGINS = [
    origin for origin in env.list(
        "CSRF_TRUSTED_ORIGINS",
        default=[],
    )
    if origin
]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=not DEBUG)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=31536000 if not DEBUG else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)
SESSION_COOKIE_HTTPONLY = env.bool("SESSION_COOKIE_HTTPONLY", default=True)
SESSION_COOKIE_SAMESITE = env("SESSION_COOKIE_SAMESITE", default="Lax")
ADMIN_SESSION_COOKIE_NAME = env("ADMIN_SESSION_COOKIE_NAME", default="admin_sessionid")
CSRF_COOKIE_SAMESITE = env("CSRF_COOKIE_SAMESITE", default="Lax")
CONTENT_SECURITY_POLICY_REPORT_ONLY = env.bool("CONTENT_SECURITY_POLICY_REPORT_ONLY", default=True)
CONTENT_SECURITY_POLICY = env(
    "CONTENT_SECURITY_POLICY",
    default=(
        "default-src 'self'; "
        "script-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdn.jsdelivr.net; "
        "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; "
        "img-src 'self' data: https:; "
        "font-src 'self' data: https://fonts.gstatic.com; "
        "connect-src 'self'; "
        "frame-ancestors 'none'; "
        "base-uri 'self'; "
        "form-action 'self'; "
        "object-src 'none'"
    ),
)
CROSS_ORIGIN_RESOURCE_POLICY = env("CROSS_ORIGIN_RESOURCE_POLICY", default="same-origin")

# Application definition

INSTALLED_APPS = [
    #Installed_apps with proirity
    'admin_soft',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    
    #Installed_apps
    'django_celery_results',
    'bootstrap4',
    'cloudinary_storage',
    'cloudinary',
    'django_filters',
    'django_tables2',
    'client_profile',
    'scrapper',
    'contact',
    # 'silk',
    
    # Plotlydash
    'channels',
    'django_plotly_dash.apps.DjangoPlotlyDashConfig',
    'dashboard',
    'dpd_static_support',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'project.admin_session.AdminSessionCookieMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #whitenoise for staticfile
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "project.security_headers.SecurityHeadersMiddleware",

    # Plotlydash
    'django_plotly_dash.middleware.BaseMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',

    # silk
    # 'silk.middleware.SilkyMiddleware',

]

X_FRAME_OPTIONS = 'SAMEORIGIN'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [env('CHANNEL_REDIS_URL', default=env('REDIS_URL', default='redis://127.0.0.1:6379/2'))],
        },
    },
}

# # Define ASGI application
ASGI_APPLICATION = 'project.asgi.application'


# Staticfiles finders for locating dash app assets and related files

STATICFILES_FINDERS = [

    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder',
]

PLOTLY_COMPONENTS = [
    'dpd_components',
    # Other components, as needed
    'dash_bootstrap_components',
    'dpd_static_support',
]


ROOT_URLCONF = 'project.urls'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # or your chosen backend

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

USE_PROD_DB = env.bool("USE_PROD_DB", default=False)
PROD_DB_URL = env("PROD_DB_URL", default="")
LOCAL_DB_NAME = env("LOCAL_DB_NAME", default="Ecomman_local")
LOCAL_DB_USER = env("LOCAL_DB_USER", default="postgres")
LOCAL_DB_PASSWORD = env("LOCAL_DB_PASSWORD", default="")
LOCAL_DB_HOST = env("LOCAL_DB_HOST", default="127.0.0.1")
LOCAL_DB_PORT = env("LOCAL_DB_PORT", default="5432")

if USE_PROD_DB and PROD_DB_URL:
    DATABASE_URL = PROD_DB_URL
    DATABASES = {
        "default": dj_database_url.parse(
            PROD_DB_URL,
            conn_max_age=600,
            ssl_require=True,
        )
    }
else:
    DATABASE_URL = (
        f"postgresql://{quote(LOCAL_DB_USER)}:{quote(LOCAL_DB_PASSWORD)}"
        f"@{LOCAL_DB_HOST}:{LOCAL_DB_PORT}/{quote(LOCAL_DB_NAME)}"
    )
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": LOCAL_DB_NAME,
            "USER": LOCAL_DB_USER,
            "PASSWORD": LOCAL_DB_PASSWORD,
            "HOST": LOCAL_DB_HOST,
            "PORT": LOCAL_DB_PORT,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Cairo'
USE_TZ = True

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
# STATICFILES_LOCATION = 'static'
STATIC_URL = '/static/'
# STATIC_ROOT = 'static'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),  # Make sure the path is correct
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATICFILES_STORAGE="whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = '/media/'
STORAGE_ROOT = Path(env('STORAGE_ROOT', default=str(BASE_DIR)).strip() or str(BASE_DIR)).resolve()
MEDIA_ROOT = STORAGE_ROOT / 'media'
if ENVIRONMENT == 'development':
    pass
else:
    DEFAULT_FILE_STORAGE= 'cloudinary_storage.storage.MediaCloudinaryStorage'
    CLOUDINARY_STORAGE =  {'CLOUDINARY_URL': env('CLOUDINARY_URL')}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    "admin_soft.authentication.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/day",
        "user": "1000/day",
        "login": "5/min",
        "register": "5/hour",
        "email_verification": "5/hour",
        "password_reset": "5/hour",
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

LOGIN_LOCKOUT_FAILURE_LIMIT = env.int("LOGIN_LOCKOUT_FAILURE_LIMIT", default=5)
LOGIN_LOCKOUT_MINUTES = env.int("LOGIN_LOCKOUT_MINUTES", default=15)
EMAIL_VERIFICATION_OTP_MINUTES = env.int("EMAIL_VERIFICATION_OTP_MINUTES", default=10)


# Celery settings

REDIS_URL = env('REDIS_URL', default='redis://127.0.0.1:6379/2')
CHANNEL_REDIS_URL = env('CHANNEL_REDIS_URL', default=REDIS_URL)
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default=REDIS_URL)
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default=REDIS_URL)
CELERY_TASK_DEFAULT_QUEUE = env('CELERY_TASK_DEFAULT_QUEUE', default='default')
CELERY_TASK_ROUTES = {
    'scrapper.tasks.scheduled_products_scraper': {'queue': 'scraping'},
    'scrapper.tasks.scheduled_bulk_scraper': {'queue': 'scraping'},
    'scrapper.tasks.scrape_user_products_task': {'queue': 'scraping'},
    'scrapper.tasks.scrape_user_Bulk_product_task': {'queue': 'scraping'},
    'dashboard.tasks.refresh_materialized_views': {'queue': 'maintenance'},
}
CELERY_TASK_CREATE_MISSING_QUEUES = True


CELERY_BEAT_SCHEDULE = {
    'product-scrape-every-12-hours': {
        'task': 'scrapper.tasks.scheduled_products_scraper',
        'schedule': 43200.0,  # 12 hours
    },
    'bulk-scrape-every-12-hours': {
        'task': 'scrapper.tasks.scheduled_bulk_scraper',
        'schedule': 43200.0,  # 12 hours
    },
        'refresh-materialized-view-24-hours': { 
        'task': 'dashboard.tasks.refresh_materialized_views', 
        'schedule': 86400.0,  # 24 hours
    },
    #     'cache-data-every-24-hours': { 
    #     'task': 'dashboard.tasks.caching_data', 
    #     'schedule': 86400.0,  # 24 hours
    # },

}

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Cairo'
CELERY_ENABLE_UTC = True


CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = env.int('CELERY_WORKER_PREFETCH_MULTIPLIER', default=1)
CELERY_TASK_SOFT_TIME_LIMIT = env.int('CELERY_TASK_SOFT_TIME_LIMIT', default=120)
CELERY_TASK_TIME_LIMIT = env.int('CELERY_TASK_TIME_LIMIT', default=180)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_RESULT_EXPIRES = env.int('CELERY_RESULT_EXPIRES', default=3600)
CELERY_TASK_IGNORE_RESULT = env.bool('CELERY_TASK_IGNORE_RESULT', default=True)

LOG_LEVEL = env('LOG_LEVEL', default='INFO')
DJANGO_LOG_LEVEL = env('DJANGO_LOG_LEVEL', default=LOG_LEVEL)
CELERY_LOG_LEVEL = env('CELERY_LOG_LEVEL', default=LOG_LEVEL)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s %(levelname)s [%(name)s] %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': False,
        },
        'celery': {
            'handlers': ['console'],
            'level': CELERY_LOG_LEVEL,
            'propagate': False,
        },
        'celery.beat': {
            'handlers': ['console'],
            'level': CELERY_LOG_LEVEL,
            'propagate': False,
        },
    },
}

# Chaches configuratio
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': env('DJANGO_CACHE_URL', default=REDIS_URL),
        'KEY_PREFIX': env('REDIS_KEY_PREFIX', default='ecomman:local'),
    }
}


LOGIN_REDIRECT_URL = 'dashboard:index' #'accounts:profile'
LOGOUT_REDIRECT_URL = 'login'
# LOGIN_URL = 'login'

FRONTEND_BASE_URL = env("FRONTEND_BASE_URL", default="http://127.0.0.1:8000")

# Contact model
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = True
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=EMAIL_HOST_USER)
EMAIL_FROM_NAME = env("EMAIL_FROM_NAME", default="Ecomman")
EMAIL_BRAND_NAME = env("EMAIL_BRAND_NAME", default="Ecomman")
EMAIL_WEBSITE_URL = env("EMAIL_WEBSITE_URL", default=FRONTEND_BASE_URL)
EMAIL_LOGO_URL = env("EMAIL_LOGO_URL", default=f"{FRONTEND_BASE_URL.rstrip('/')}{STATIC_URL}img/logos/ECOM_logo.svg")
EMAIL_SOCIAL_LINKEDIN_URL = env("EMAIL_SOCIAL_LINKEDIN_URL", default="")
EMAIL_SOCIAL_FACEBOOK_URL = env("EMAIL_SOCIAL_FACEBOOK_URL", default="")
SUPPORT_EMAIL = env("SUPPORT_EMAIL", default=DEFAULT_FROM_EMAIL)



