# Generated by Django 5.0.7 on 2024-08-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_profile', '0003_alter_product_amazon_link_alter_product_dawa_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dawa_price', models.FloatField(blank=True, null=True)),
                ('nahdi_price', models.FloatField(blank=True, null=True)),
                ('amazon_price', models.FloatField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_profile.product')),
            ],
        ),
    ]
