# Generated by Django 5.0.7 on 2024-08-18 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_tables', to=settings.AUTH_USER_MODEL),
        ),
    ]
