# Generated by Django 5.0.7 on 2024-08-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_alter_pinnedtable_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinnedtable',
            old_name='data',
            new_name='table_data',
        ),
    ]
