# Generated by Django 5.0.7 on 2024-08-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0006_scrapeddata_pinned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinnedtable',
            name='table_data',
        ),
    ]
