# Generated by Django 5.0.7 on 2024-08-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_remove_pinnedtable_table_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinnedTable',
        ),
    ]
