# Generated by Django 5.0.7 on 2024-08-19 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_delete_pinnedtable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapeddata',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_data', to=settings.AUTH_USER_MODEL),
        ),
    ]
