# Generated by Django 5.0.7 on 2024-08-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_alter_scrapeddata_pinned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='amazon_shipping',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='amazon_sold_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
