# Generated by Django 5.0.7 on 2024-09-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0010_scrapeddata_amazon_shipping_and_more'),
    ]

    operations = [
    ]
