# Generated by Django 5.0.7 on 2024-09-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0011_auto_20240904_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='pinned_by',
        ),
    ]
