# Generated by Django 5.0.7 on 2024-09-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0013_scrapeddata_pinned_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapeddata',
            name='pinned_by',
        ),
    ]
