# Generated by Django 5.0.7 on 2024-10-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0014_remove_scrapeddata_pinned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='amazon_availability_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='amazon_choice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='amazon_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='amazon_sold_count',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='amazon_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='dawa_availability_info',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='dawa_is_in_stock_msi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='dawa_offer_text_notag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='dawa_original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='dawa_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='nahdi_availability_info',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='nahdi_limited_stock',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='nahdi_ordered_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='nahdi_original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='nahdi_sold_out',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='nahdi_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='amazon_shipping',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='amazon_sold_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
