# Generated by Django 5.0.7 on 2024-11-03 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0029_alter_productaccountlinkid_identifier'),
        ('scrapper', '0015_scrapeddata_amazon_availability_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedBulkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('key_name', models.CharField(max_length=100)),
                ('amazon_price', models.FloatField(blank=True, null=True)),
                ('amazon_title', models.CharField(blank=True, max_length=200, null=True)),
                ('amazon_sku', models.CharField(blank=True, max_length=200, null=True)),
                ('amazon_original_price', models.FloatField(blank=True, null=True)),
                ('dawa_price', models.FloatField(blank=True, null=True)),
                ('dawa_title', models.CharField(blank=True, max_length=200, null=True)),
                ('dawa_sku', models.CharField(blank=True, max_length=200, null=True)),
                ('dawa_original_price', models.FloatField(blank=True, null=True)),
                ('dawa_offer_text_notag', models.CharField(blank=True, max_length=200, null=True)),
                ('nahdi_price', models.FloatField(blank=True, null=True)),
                ('nahdi_title', models.CharField(blank=True, max_length=200, null=True)),
                ('nahdi_sku', models.CharField(blank=True, max_length=200, null=True)),
                ('nahdi_original_price', models.FloatField(blank=True, null=True)),
                ('nahdi_ordered_qty', models.FloatField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_profile.product')),
            ],
        ),
    ]
