# Generated by Django 5.0.7 on 2024-11-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0016_scrapedbulkdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedbulkdata',
            name='product',
        ),
    ]
