# Generated by Django 5.0.7 on 2024-11-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0017_remove_scrapedbulkdata_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='noon_availability_info',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='noon_original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='noon_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='noon_sold_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='noon_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
