# Generated by Django 5.0.7 on 2024-11-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0018_scrapeddata_noon_availability_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='noon_availability_info',
            new_name='noon_sa_availability_info',
        ),
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='noon_original_price',
            new_name='noon_sa_original_price',
        ),
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='noon_price',
            new_name='noon_sa_price',
        ),
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='noon_sold_by',
            new_name='noon_sa_sold_by',
        ),
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='noon_title',
            new_name='noon_sa_title',
        ),
    ]
