# Generated by Django 5.0.7 on 2024-11-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0019_rename_noon_availability_info_scrapeddata_noon_sa_availability_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='noon_sa_price',
            new_name='noon_sa_temp_price',
        ),
    ]
