# Generated by Django 5.0.7 on 2024-11-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0020_rename_noon_sa_price_scrapeddata_noon_sa_temp_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapeddata',
            old_name='noon_sa_temp_price',
            new_name='noon_sa_price',
        ),
    ]
