# Generated by Django 5.0.7 on 2024-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0021_rename_noon_sa_temp_price_scrapeddata_noon_sa_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='noon_sa_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
