# Generated by Django 5.0.7 on 2024-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0022_scrapeddata_noon_sa_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapeddata',
            name='dawa_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapeddata',
            name='nahdi_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
