# Generated by Django 5.0.7 on 2024-11-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0023_scrapeddata_dawa_discount_scrapeddata_nahdi_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedbulkdata',
            name='amazon_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedbulkdata',
            name='dawa_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedbulkdata',
            name='nahdi_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedbulkdata',
            name='noon_sa_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedbulkdata',
            name='noon_sa_original_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedbulkdata',
            name='noon_sa_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scrapedbulkdata',
            name='noon_sa_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
