# Generated by Django 5.0.7 on 2024-11-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0024_scrapedbulkdata_amazon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedbulkdata',
            name='noon_sa_sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
