# Generated by Django 5.0.7 on 2024-11-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0025_scrapedbulkdata_noon_sa_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedbulkdata',
            name='amazon_sku',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedbulkdata',
            name='amazon_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedbulkdata',
            name='dawa_sku',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedbulkdata',
            name='dawa_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedbulkdata',
            name='nahdi_sku',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedbulkdata',
            name='nahdi_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedbulkdata',
            name='noon_sa_sku',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedbulkdata',
            name='noon_sa_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='amazon_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='dawa_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='nahdi_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapeddata',
            name='noon_sa_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
