# Generated by Django 5.0.7 on 2024-07-31 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASIN', models.CharField(max_length=100, unique=True)),
                ('TITLE', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('RSP', models.FloatField()),
                ('RSP_VAT', models.FloatField()),
                ('Amazon_Link', models.URLField()),
                ('Nahdi_Link', models.URLField()),
                ('Dawa_Link', models.URLField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='client_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='client_profile.product')),
            ],
        ),
    ]
