# Generated by Django 5.0.7 on 2024-07-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0002_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Amazon_Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Dawa_Link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Nahdi_Link',
            field=models.URLField(null=True),
        ),
    ]
