# Generated by Django 5.0.7 on 2024-08-14 16:00

import client_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0003_alter_product_amazon_link_alter_product_dawa_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=client_profile.models.product_photo_upload_path),
        ),
    ]
