# Generated by Django 5.0.7 on 2024-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0004_alter_photo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned_tables',
            field=models.ManyToManyField(blank=True, to='client_profile.pinnedtable'),
        ),
    ]
