# Generated by Django 5.0.7 on 2024-08-21 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0005_pinnedtable_profile_pinned_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('amazon', 'amazon'), ('dawa', 'dawa'), ('nahdi', 'nahdi')], max_length=100)),
                ('domain', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Amazon_Link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Dawa_Link',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Nahdi_Link',
        ),
        migrations.CreateModel(
            name='ProductAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='client_profile.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_links', to='client_profile.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='accounts',
            field=models.ManyToManyField(through='client_profile.ProductAccountLink', to='client_profile.account'),
        ),
    ]
