# Generated by Django 5.0.7 on 2024-08-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0006_account_remove_product_amazon_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='account_id',
            field=models.CharField(choices=[('amazon', 'amazon url'), ('dawa', 'al dawa url'), ('nahdi', 'nahdi url')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='productaccountlink',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
