# Generated by Django 5.0.7 on 2024-08-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0007_remove_account_name_account_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_id',
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(choices=[('amazon', 'amazon'), ('dawa', 'dawa'), ('nahdi', 'nahdi')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='domain',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='productaccountlink',
            name='url',
            field=models.URLField(),
        ),
    ]
