# Generated by Django 5.0.7 on 2024-08-25 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0008_remove_account_account_id_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_profile.profile'),
        ),
    ]
