# Generated by Django 5.0.7 on 2024-08-25 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0009_alter_product_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='client_profile.profile'),
        ),
    ]
