# Generated by Django 5.0.7 on 2024-08-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0011_keyword_product_category_product_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductKeyword',
        ),
    ]
