# Generated by Django 5.0.7 on 2024-08-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0012_delete_productkeyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_profile.keyword')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client_profile.product')),
            ],
        ),
    ]
