# Generated by Django 5.0.7 on 2024-08-27 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0014_promoplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_plans', to='client_profile.product'),
        ),
    ]
