# Generated by Django 5.0.7 on 2024-08-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0015_alter_promoplan_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoplan',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promo_plans', to='client_profile.profile'),
            preserve_default=False,
        ),
    ]
