# Generated by Django 5.0.7 on 2024-08-27 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0016_promoplan_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoplan',
            name='is_on_sale',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
