# Generated by Django 5.0.7 on 2024-08-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0017_alter_promoplan_is_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ASIN',
            field=models.CharField(max_length=100),
        ),
    ]
