# Generated by Django 5.0.7 on 2024-09-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0018_alter_product_asin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='productkeyword',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='productkeyword',
            name='product',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
        migrations.DeleteModel(
            name='ProductKeyword',
        ),
    ]
