# Generated by Django 5.0.7 on 2024-09-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0019_remove_product_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
