# Generated by Django 5.0.7 on 2024-09-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0020_remove_product_category_remove_product_subcategory'),
    ]

    operations = [

    ]
