# Generated by Django 5.0.7 on 2024-10-03 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0024_product_category_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('amazon', 'amazon'), ('dawa', 'dawa'), ('nahdi', 'nahdi')], max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAccountLinkId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=300)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_id_links', to='client_profile.account_id')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_id_links', to='client_profile.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='accounts_id',
            field=models.ManyToManyField(through='client_profile.ProductAccountLinkId', to='client_profile.account_id'),
        ),
    ]
