# Generated by Django 5.0.7 on 2024-10-03 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0025_account_id_productaccountlinkid_product_accounts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ASIN',
        ),
    ]
