# Generated by Django 5.0.7 on 2024-10-03 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0026_remove_product_asin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_id',
            name='identifier',
        ),
    ]
