# Generated by Django 5.0.7 on 2024-10-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0027_remove_account_id_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_description',
        ),
    ]
