# Generated by Django 5.0.7 on 2024-10-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0028_remove_photo_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productaccountlinkid',
            name='identifier',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
