# Generated by Django 5.0.7 on 2024-11-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0029_alter_productaccountlinkid_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='productaccountlink',
            name='account',
        ),
        migrations.RemoveField(
            model_name='productaccountlink',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='is_competitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account_id',
            name='name',
            field=models.CharField(choices=[('amazon', 'amazon'), ('dawa', 'dawa'), ('nahdi', 'nahdi'), ('noon_sa', 'noon_sa')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='RSP',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='RSP_VAT',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='ProductAccountLink',
        ),
    ]
