# Generated by Django 5.0.7 on 2025-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0030_remove_product_accounts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='competitor_references',
            field=models.ManyToManyField(blank=True, related_name='referenced_by', to='client_profile.product'),
        ),
    ]
