# Generated by Django 5.0.7 on 2025-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0031_product_competitor_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='TITLE',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
