# Generated by Django 5.0.7 on 2026-07-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_profile', '0036_rename_product_title_to_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='key',
            field=models.CharField(choices=[('amazon_sa', 'Amazon SA'), ('al_dawa', 'Al-Dawa'), ('nahdi', 'Nahdi'), ('nice_one', 'Nice One'), ('ana_ninja', 'Ninja'), ('noon_sa', 'Noon SA')], max_length=50, unique=True),
        ),
    ]
